export {default as AboutUsPage} from './AboutUsPage/AboutUsPage'
export {default as CartPage} from './CartPage/CartPage'
export {default as ErrorPage} from './ErrorPage/ErrorPage'
export {default as HomePage} from './HomePage/HomePage'
export {default as MenuPage} from './MenuPage/MenuPage'